### ISSUE TITLE
Authorization required for rendersnake dependency

### ISSUE THREAD

**Issue by HerbertSchuurmans** [emicklei/critter#14]
Hi,
Running "mvn clean install" results in the following failure message:

```[ERROR] Failed to execute goal on project critter: Could not resolve dependencies for project com.philemonworks:critter:jar:1.1.4: Failed to collect dependencies at org.rendersnake:rendersnake:jar:1.7.3: Failed to read artifact descriptor for org.rendersnake:rendersnake:jar:1.7.3: Could not transfer artifact org.rendersnake:rendersnake:pom:1.7.3 from/to rendershark-repo (http://rendershark.googlecode.com/svn/repo): Not authorized , ReasonPhrase:Authorization Required. -> [Help 1]```

It seems that the rendershark-repo and rendersnake-repo are protected and the emicklei-repo doens't seems to exist.
Do you have an alternative for these repo's?

Regards,

Herbert

**Comment by emicklei** [comment]
use rendersnake 1.9.0

i need to update then critter pom soon. thx for reporting this

On Thursday, June 25, 2015, HerbertSchuurmans <notifications@github.com>
wrote:

> Hi,
> Running "mvn clean install" results in the following failure message:
>
> [ERROR] Failed to execute goal on project critter: Could not resolve
> dependencies for project com.philemonworks:critter:jar:1.1.4: Failed to
> collect dependencies at org.rendersnake:rendersnake:jar:1.7.3: Failed to
> read artifact descriptor for org.rendersnake:rendersnake:jar:1.7.3: Could
> not transfer artifact org.rendersnake:rendersnake:pom:1.7.3 from/to
> rendershark-repo (http://rendershark.googlecode.com/svn/repo): Not
> authorized , ReasonPhrase:Authorization Required. -> [Help 1]
>
> It seems that the rendershark-repo and rendersnake-repo are protected and
> the emicklei-repo doens't seems to exist.
> Do you have an alternative for these repo's?
>
> Regards,
>
> Herbert
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emicklei/critter/issues/14>.
>


-- 
^ Ernest Micklei

http://ernestmicklei.com

**Comment by emicklei** [comment]
fixed with commit 23e5015d0c43187b59ec96f8c32b2aae1170b584
